### ISSUE TITLE
Error: Error parsing index.html:  TypeError: Cannot read property 'is' of null

### ISSUE THREAD

**Issue by benhjt** [Polymer/vscode-plugin#36]
I have created a basic `index.html` in an empty folder:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>

</body>
</html>
```

When I add a `style` tag to the head, I immediately get the following error in the console: 

[Error - 12:36:55] Error: Error parsing bower_components/index.html:
 TypeError: Cannot read property 'is' of null
    at Parser.parseDeclarationOrRuleset (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\node_modules\shady-css-parser\dist\shady-css\parser.js:192:33)
    at Parser.parseRule (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRules (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\node_modules\shady-css-parser\dist\shady-css\parser.js:62:25)
    at Parser.parseStylesheet (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\node_modules\shady-css-parser\dist\shady-css\parser.js:55:47)
    at Parser.parse (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\node_modules\shady-css-parser\dist\shady-css\parser.js:51:19)
    at CssParser.parse (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\css\css-parser.js:22:32)
    at Analyzer._parseContents (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:358:27)
    at Analyzer.<anonymous> (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:216:35)
    at next (<anonymous>)
    at C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:20:65
    at Analyzer._parseContents (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:364:19)
    at Analyzer.<anonymous> (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:216:35)
    at next (<anonymous>)
    at C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:20:65
    at __awaiter (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:16:12)
    at Analyzer._scanSource (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:214:16)
    at Analyzer.<anonymous> (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:270:52)
    at next (<anonymous>)
    at C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:20:65
    at __awaiter (C:\Users\benhjt\\.vscode\extensions\polymer.polymer-ide-0.1.2\server\node_modules\polymer-analyzer\lib\analyzer.js:16:12)

I'm not sure why this is reporting as being in a bower_components folder as the index.html is in a completely empty folder. Every time I type to edit the style, the output console opens.

**Comment by quangld** [comment]
Yes, I can confirm: The extension still pushes error messages to the OUTPUT window. It's just a little big annoying if you're working on a small screen, and you have to minimize that windows every time it pops up.
Here is one of these errors
- Error: No parser for for file type

**Comment by rictic** [comment]
These errors have all been fixed. Please file new bugs if you ever see them again!
